### ISSUE TITLE
Fails to build with sundials-6.4.0

### ISSUE THREAD

**Issue by yurivict** [boutproject/BOUT-dev#2617]
```
In file included from /usr/ports/science/bout++/work/BOUT-dev-4.4.2/include/boutexception.hxx:7,
                 from /usr/ports/science/bout++/work/BOUT-dev-4.4.2/include/bout/solver.hxx:40:
/usr/local/lib/gcc12/include/c++/exception:124:8: note: declared here
  124 |   bool uncaught_exception() _GLIBCXX_USE_NOEXCEPT __attribute__ ((__pure__));
      |        ^~~~~~~~~~~~~~~~~~
/usr/ports/science/bout++/work/BOUT-dev-4.4.2/src/solver/impls/ida/ida.cxx: In member function 'virtual int IdaSolver::init(int, BoutReal)':
/usr/ports/science/bout++/work/BOUT-dev-4.4.2/src/solver/impls/ida/ida.cxx:141:30: error: too few arguments to function '_generic_N_Vector* N_VNew_Parallel(MPI_Comm, sunindextype, sunindextype, SUNContext)'
  141 |   if ((uvec = N_VNew_Parallel(BoutComm::get(), local_N, neq)) == nullptr)
      |               ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/ports/science/bout++/work/BOUT-dev-4.4.2/src/solver/impls/ida/ida.hxx:43:
/usr/local/include/nvector/nvector_parallel.h:93:26: note: declared here
   93 | SUNDIALS_EXPORT N_Vector N_VNew_Parallel(MPI_Comm comm,
      |                          ^~~~~~~~~~~~~~~
/usr/ports/science/bout++/work/BOUT-dev-4.4.2/src/solver/impls/ida/ida.cxx:143:31: error: too few arguments to function '_generic_N_Vector* N_VNew_Parallel(MPI_Comm, sunindextype, sunindextype, SUNContext)'
  143 |   if ((duvec = N_VNew_Parallel(BoutComm::get(), local_N, neq)) == nullptr)
      |                ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/nvector/nvector_parallel.h:93:26: note: declared here
   93 | SUNDIALS_EXPORT N_Vector N_VNew_Parallel(MPI_Comm comm,
      |                          ^~~~~~~~~~~~~~~
```

**Comment by dschwoerer** [comment]
Fixed in https://github.com/boutproject/BOUT-dev/pull/2517

I would suggest trying 5.0.0a0.dev10461 (you can get tarballs [here](https://pypi.org/project/boutpp-nightly/#files))
