### ISSUE TITLE
elm-pb example doesn't compile

### ISSUE THREAD

**Issue by JosephThomasParker** [boutproject/BOUT-dev#1507]
In `next`, `elm-pb` doesn't compile due to the undeclared variable `delta_e_inv`:

```
elm_pb.cxx: In function 'int physics_init(bool)':
elm_pb.cxx:1023:25: error: 'delta_e_inv' was not declared in this scope
   aparSolver->setCoefA(-delta_e_inv * N0 * N0);
```

This was introduced in 502244a58e2d9.  

(Btw, this looks like this is adding electromagnetic effects into elm-pb.  Since we use elm-pb as a performance benchmark, it might be good to keep a separate electrostatic version.)

**Comment by dschwoerer** [comment]
Any update on this?

**Comment by bendudson** [comment]
Sorry, it's on my to-do list

**Comment by ZedThree** [comment]
Fixed in #1688
